### ISSUE TITLE
AES-Key

### ISSUE THREAD

**Issue by comtechnik** [tirolerstefan/kaifa#18]
Hallo Stefan,
ich komme auch aus Tirol (Unterland), habe mein Kaifa MA309 Smart Meter vor 1 Monat von der Tiwag erhalten.
Leider weis ich nicht genau wie ich den AES-Key von der Tiwag erhalte.
Den MBUS-Slave-Modul-Master-Slave-Kommunikation Stick bekomme ich die nächsten Tage.
Wie geh ich am besten vor um meinen Smart Meter auszulesen.
Funktioniert das ganze mit einem Raspberry oder wie machst du das?
Wäre dir sehr dankbar für die Hilfe.

SG Robert

**Comment by tirolerstefan** [comment]
Hi Robert, den Key kannst du übers Tinetz-Portal bestellen (oder such im Internet einfach nach "Tinetz Kundenschnittstelle", dann kommst du zu einem PDF).

Ja, du brauchst einen RPi, schau dir am besten noch einmal meine Readme an: https://github.com/tirolerstefan/kaifa/blob/master/README.md

Grüße, Stefan

**Comment by comtechnik** [comment]
Hallo Stefan,
Hab es endlich geschafft, Daten werden ausgelesen, wie kann ich es machen das bei Neustart alles von selbst aktiviert wird da die Übertragung nicht von selbst startet?
Hab noch ne Frage zu den Daten, bei mir werden nur 2.8.0 und 1.8.0 ausgelesen,
Gibt es Möglichkeiten mehr auszulesen, z.b. Ströme und Watt der einzelnen Phasen, bei mir werden am display auch noch 1.8.1 und 1.8.2 und 1.6.0 angezeigt.

**Comment by boredomwontgetus** [comment]
> Hab es endlich geschafft, Daten werden ausgelesen, wie kann ich es machen das bei Neustart alles von selbst aktiviert wird da die Übertragung nicht von selbst startet?

Könntest du mal den output von `systemctl status kaifareader` nach einem reboot posten?

**Comment by comtechnik** [comment]
pi@smartmeter:~ $ systemctl status kaifareader
● kaifareader.service - kaifareader
     Loaded: loaded (/lib/systemd/system/kaifareader.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-06-02 19:17:44 CEST; 1 day 14h ago
    Process: 466 ExecStartPre=/bin/mkdir -p /var/run/kaifareader (code=exited, status=0/SUCCESS)
    Process: 478 ExecStartPre=/bin/mkdir -p /var/log/kaifareader (code=exited, status=0/SUCCESS)
    Process: 479 ExecStartPre=/bin/chmod 777 /var/run/kaifareader (code=exited, status=0/SUCCESS)
    Process: 482 ExecStartPre=/bin/chmod 777 /var/log/kaifareader (code=exited, status=0/SUCCESS)
    Process: 483 ExecStart=/usr/bin/python3 /usr/lib/kaifareader/kaifareader.py (code=exited, status=40)
   Main PID: 483 (code=exited, status=40)
        CPU: 1.451s

Jun 02 19:17:40 smartmeter systemd[1]: Starting kaifareader...
Jun 02 19:17:41 smartmeter systemd[1]: Started kaifareader.
Jun 02 19:17:44 smartmeter systemd[1]: kaifareader.service: Main process exited, code=exited, status=40/n/a
Jun 02 19:17:44 smartmeter systemd[1]: kaifareader.service: Failed with result 'exit-code'.
Jun 02 19:17:44 smartmeter systemd[1]: kaifareader.service: Consumed 1.451s CPU time.
pi@smartmeter:~ $


vieleicht nützt dir auch diese meldung etwas wenn Activ: running ist

pi@smartmeter:~ $ sudo python3 /home/pi/Desktop/kaifareader.py
Traceback (most recent call last):
  File "/home/pi/Desktop/kaifareader.py", line 53, in <module>
    daten = ser.read(size=282).hex()
  File "/usr/local/lib/python3.9/dist-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
pi@smartmeter:~ $

**Comment by boredomwontgetus** [comment]
For the record: Wurde bilateral gelöst.

**Comment by comtechnik** [comment]
Hallo Stefan,
Danke für die schnelle Antwort, ist der Key der Pin?

SG Robert

Stefan ***@***.***> schrieb am Mo., 16. Mai 2022, 18:08:

**Comment by tirolerstefan** [comment]
Hi,

nein, der Key ist kein Pin.

LG Stefan

RD ***@***.***> schrieb am Di., 11. Okt. 2022, 10:49:

> Hallo Stefan,
> Danke für die schnelle Antwort, ist der Key der Pin?
>
> SG Robert
